# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bbab44a87dc1cbed0fc6361c03a761fb1c727ac087696a2632ebb94f5174d35fabc2f402f6b604e399fc326a9421f176aa916ab4d778e7a38aca333b9635c992

test:
  secret_key_base: f2f8b8b870304f0504f0d90a27052ee9ea83764e44d0daba40ad5f15d73fe2ac943aadd89a0175b4dd434330c3539f2a2db5553e56e55cc28be55d2e2f1057bf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
